### ISSUE TITLE
kubernetes-charm-libraries multus act on any config_changed event without config validation

### ISSUE THREAD

**Issue by gatici** [canonical/kubernetes-charm-libraries#16]
Multus Library is acting for any config_changed event without config validation.
 https://github.com/canonical/kubernetes-charm-libraries/blob/264ac5d1f380c86d324ad1cd7e27db2044155358/lib/charms/kubernetes_charm_libraries/v0/multus.py#L502

We discussed this issue in one of our daily and decided to trigger a custom event in the charm side then library can act to this custom event instead of config_changed event.
Otherwise, we need to ignore invalid configs in the library part which makes the things messy.

https://github.com/canonical/observability-libs/blob/main/lib/charms/observability_libs/v0/kubernetes_compute_resources_patch.py#L462

**Comment by DanielArndt** [comment]
@gatici Can this be closed now that #17 is merged?

**Comment by gatici** [comment]
The problem is fixed.
